name: Python application

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with PyLint
      run: |
        pip install pylint
        find . -iname "*.py" | xargs pylint
    - name: Test Lambdas
      run: |
        pip install nose
        python -m nose lambdas
